### PR TITLE
Provide option to overwrite the dragged files

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
My preferred workflow is to drag the icons I want to use from the
gallery into Xcode, then change colours in place.

This option allows me to drag files to the colour changer, and not have
to select the destination folder.

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
I'm new to github pull requests - so not sure if this pull request sends through all my commits, or if I need to create separate requests.

what I'd like you to see is:
-Provide option to overwrite the dragged files 
-save colour in a preference 
-Adjust min/max size

**Comment by ruddfawcett** [comment]
Thanks for the pull request @ConfusedVorlon.  If you could post a screenshot of the new UI/menu items, that would be awesome!

**Comment by jpwain** [comment]
@ConfusedVorlon Sounds awesome! Overwriting dragged files would indeed be handy. 

An another approach might be a "fill queue, set options, then process" flow like filename changing tools. See this screenshot of Name Mangler: http://screenshots.en.sftcdn.net/en/scrn/64000/64143/3_overview_large.jpg

You'd fill a list queue with the icons you want to modify, then select a color, then hit the go button. If you then picked another color and hit the go button again, the same files (since they're still in the list) would be changed again.

Digression from this pull request, but something to think about.

**Comment by ConfusedVorlon** [comment]
2014-09-19 05 48 13 pm

that's my change  - it isn't complicated! 
I have been using it this afternoon, and fine it much easier to work with.

**Comment by ConfusedVorlon** [comment]
re the queue system, it's more complex than I would need - but perhaps others might like it.

**Comment by ruddfawcett** [comment]
@ConfusedVorlon I'm assuming 14278f0 closes #4?

**Comment by ConfusedVorlon** [comment]
yes  14278f0 closes #4

**Pull request merged**
